### ISSUE TITLE
Can these codes run successfully in VASP?

### ISSUE THREAD

**Issue by lycheehoo** [Probe-Particle/PPSTM#17]
Dear editor,
I just wonder how to use these codes in VASP to simulate STM or nc-AFM images, thank you very much.

**Comment by ondrejkrejci** [comment]
Hello,

As for nc-AFM images with flexible or at least non-reactive tip apex (CO, Xe, O ... ): Yes, - this can be done through the [**ppafm** code](https://github.com/Probe-Particle/ppafm). The only necessary thing is to print `LOCPOT` via adding `LVHAR = .TRUE.` into your _INCAR_. Please consult with the [ppafm wiki](https://github.com/Probe-Particle/ppafm/wiki) or start an issue there, if you are unsure about anything on that side.

As for the STM images  with flexible tip apex (CO, Xe, O ... ) with output purely from **VASP**: No and since the code is depending on _Linear Combination of Atomic Orbitals_ (LCAO) formalism, there is no easy way how to get important data from the _Plane Wave_ formalism of VASP. There is even no development in this direction. So if you need STM images, when the tip is really bending=flexing, then take the geometry from VASP and recalculate it with some _LCAO_ code, like **CP2K** (gpl license) or **FHI-aims** (need to apply for the license) for getting the inputs for **PPSTM**.

If you need STM images, when the tip is not flexing (there are no sharp edges in the experimental images). Then I would recommend to check work of Kristian Palotas https://www.phy.bme.hu/~palotas/res.html who is taking care of **BSCAN** and **3D-WKB-STM** which both are based on **VASP** formalism and both can do _P_ tips.


Is it clear like that?

**Comment by lycheehoo** [comment]
Thanks for your prompt and detailed reply. I am clear now and wish you all the best.
