### ISSUE TITLE
Different chirality between input molecular structure and output simulated di/dv maps

### ISSUE THREAD

**Issue by lycheehoo** [Probe-Particle/PPSTM#24]
Dear developers, when I try to simulate an isolated single molecule’s di/dv maps, I found that the output patterns were heterochiral compared to my input molecular structure. Do you know the reason for this? Thanks!

**Comment by ondrejkrejci** [comment]
Hi, please could you be more specific - show us the geometry (ideally a file), one of the outputs and the script you were using for calculating the dIdV images?
Otherwise the guessing is to wide.

**Comment by lycheehoo** [comment]
[inputfile.zip](https://github.com/Probe-Particle/PPSTM/files/14758293/inputfile.zip)
Yes, here are my input files. :)

**Comment by ondrejkrejci** [comment]
Thanks,
so 1st of all - you have a non-symmetric molecule - thus the wave-function will be mostly asymmetric. So the code is running according to my expectations.

2nd, you have selected "states" in your dIdV scan - mean that you will do the dIdV just at the energies of states, which are assymetric - to try to symmetrify your scan, you can run V-scan over -2 to +2 Volts with dV 0.1 and eta at least 0.1 (or even 0.3) when you will enlarge the contribution of other states, which could make it look more symmetrick

3rd - my guess is that more symmetric experimental image is actually caused by reorganization and broadening  the states (~effectively enlarging the eta) with the interaction with substrate.

If a full system (molecule on metal) is too large, you can just try to put 1 layer "metallic cluster" of hexagonal shape ~3 angstrom underneath. This can shift your Fermi level in comparison with experiment (dIdV willl be in different voltages) , but could help you to see whether the effect of substrate is absolutely necessary to understand the experimental images,
